version: '3'
services:
  redis:
    image: redis:6.0.9
    container_name: redis
    ports:
      - 6379:6379
  postgres:
    image: postgres:11.10
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  redash-server:
    image: redash/redash:10.0.0.b50363
    container_name: redash-server
    command: server
    ports:
      - 5000:5000
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_ADDITIONAL_QUERY_RUNNERS: "redash.query_runner.python"
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: "Sew0sQ0k-1jTe9tGx"
    depends_on:
      - postgres
      - redis
  redash-worker:
    image: redash/redash:10.0.0.b50363
    container_name: redash-worker
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_ADDITIONAL_QUERY_RUNNERS: "redash.query_runner.python"
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: "Sew0sQ0k-1jTe9tGx"
      QUEUES: "queries"
      WORKERS_COUNT: 2
    depends_on:
      - postgres
      - redis
      - redash-server
  redash-worker-scheduled-queries:
    image: redash/redash:10.0.0.b50363
    container_name: redash-worker-scheduled-queries
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_ADDITIONAL_QUERY_RUNNERS: "redash.query_runner.python"
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: "Sew0sQ0k-1jTe9tGx"
      QUEUES: "scheduled_queries"
      WORKERS_COUNT: 2
    depends_on:
      - postgres
      - redis
      - redash-server
  redash-worker-celery:
    image: redash/redash:10.0.0.b50363
    container_name: redash-worker-celery
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_ADDITIONAL_QUERY_RUNNERS: "redash.query_runner.python"
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: "Sew0sQ0k-1jTe9tGx"
      QUEUES: "celery"
      WORKERS_COUNT: 2
    depends_on:
      - postgres
      - redis
      - redash-server

