apiVersion: batch/v1
kind: Job
metadata:
  name: boring-primenumber
  namespace: doridoridoriand
spec:
  template:
    spec:
      containers:
      - name: boring-primenumber0
        image: doridoridoriand/boring_primenumber:output-oneline
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        command: ["ruby",  "exec.rb", "480000"]
      - name: boring-primenumber1
        image: doridoridoriand/boring_primenumber:output-oneline
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        command: ["ruby",  "exec.rb", "480000"]
      - name: boring-primenumber2
        image: doridoridoriand/boring_primenumber:output-oneline
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        command: ["ruby",  "exec.rb", "480000"]
      - name: boring-primenumber3
        image: doridoridoriand/boring_primenumber:output-oneline
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        command: ["ruby",  "exec.rb", "480000"]
      - name: boring-primenumber4
        image: doridoridoriand/boring_primenumber:output-oneline
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        command: ["ruby",  "exec.rb", "480000"]
      - name: boring-primenumber5
        image: doridoridoriand/boring_primenumber:output-oneline
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        command: ["ruby",  "exec.rb", "480000"]
      - name: boring-primenumber6
        image: doridoridoriand/boring_primenumber:output-oneline
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command: ["ruby",  "exec.rb", "480000"]
      - name: boring-primenumber7
        image: doridoridoriand/boring_primenumber:output-oneline
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command: ["ruby",  "exec.rb", "480000"]
      - name: boring-primenumber8
        image: doridoridoriand/boring_primenumber:output-oneline
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command: ["ruby",  "exec.rb", "480000"]
      - name: boring-primenumber9
        image: doridoridoriand/boring_primenumber:output-oneline
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command: ["ruby",  "exec.rb", "480000"]
      - name: boring-primenumber10
        image: doridoridoriand/boring_primenumber:output-oneline
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command: ["ruby",  "exec.rb", "480000"]
      - name: boring-primenumber11
        image: doridoridoriand/boring_primenumber:output-oneline
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command: ["ruby",  "exec.rb", "480000"]
      - name: boring-primenumber12
        image: doridoridoriand/boring_primenumber:output-oneline
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command: ["ruby",  "exec.rb", "480000"]
      - name: boring-primenumber13
        image: doridoridoriand/boring_primenumber:output-oneline
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command: ["ruby",  "exec.rb", "480000"]
      - name: boring-primenumber14
        image: doridoridoriand/boring_primenumber:output-oneline
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command: ["ruby",  "exec.rb", "480000"]
      restartPolicy: Never
  backoffLimit: 4
