apiVersion: apps/v1
kind: Deployment
metadata:
  name: waste-cpu-resource-deployment
  namespace: doridoridoriand
spec:
  replicas: 10
  selector:
    matchLabels:
      app: waste-cpu-resource-app-dp
  template:
    metadata:
      namespace: doridoridoriand
      labels:
        app: waste-cpu-resource-app-dp
    spec:
      containers:
        - name: waste-cpu-resource-container
          image: doridoridoriand/boring_primenumber:3.0.0-0.0.2
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1500m
              memory: 1Gi
