# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rack'
gem 'thin'
gem 'faye-websocket'
gem 'eventmachine'
gem 'pry'
