---

- address_range_list:
    - aws:
      - uri: https://ip-ranges.amazonaws.com/ip-ranges.json
        filetype: json
        gettype: normal
    - azure:
      - uri: file://file/azure/PublicIPs_20180820.xml
        filetype: xml
        gettype: local
    - gcp:
      - uri: _spf.google.com
        gettype: dig
