version: '2'
services:
  elasticsearch:
    build: es
    volems:
      - es-data:/use/share/elasticsearch/data
      - ./es/config:/usr/share/elasticsearch/config
    ports:
      - 9200:9200
    expose:
      - 9300
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  kibana:
    build: kibana
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5601:5601
volumes:
  es-data:
    driver:local

