version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    container_name: elasticsearch
    volumes:
      - ./data_directory:/use/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
  kibana:
    build: kibana
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5601:5601
  logstash:
    build: logstash
    links:
      - elasticsearch:elasticsearch
volumes:
  data_directory:
    driver: local

