cluster.name: "docker-cluster"
http.host: 0.0.0.0

discovery.zen.minimum_master_nodes: 1
discovery.type: single-node
#xpack.graph.enabled: false
#xpack.ml.enabled: false
#xpack.monitoring.enabled: false
#xpack.security.enabled: false
#xpack.watcher.enabled: false
