version: '3'
services:
  clickhouse-server:
    image: yandex/clickhouse-server:1.1
    container_name: clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse
  clickhouse-client:
    image: yandex/clickhouse-client:18.12
    container_name: clickhouse-client
    depends_on:
      - clickhouse-server
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redash
  redis:
    image: redis:5.0.9
    container_name: redis
    ports:
      - 6379:6379
  mongodb:
    image: mongo:4.0
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express:0.49
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
  postgres:
    image: postgres:9.6.18
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  redash-server:
    image: redash/redash:8.0.2.b37747
    container_name: redash-server
    command: server
    ports:
      - 5000:5000
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: veryverysecret
    depends_on:
      - postgres
      - redis
  redash-worker:
    image: redash/redash:8.0.2.b37747
    container_name: redash-worker
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
    depends_on:
      - postgres
      - redis
      - redash-server

