# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'mysql2'
gem 'pry'

# 標準ライブラリたち
gem 'bundler', :require => [
  'optparse',
  'yaml'
]
