---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uuid-api-deployment
  namespace: doridoridoriand
spec:
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      labelName: uuid-api-label
  template:
    metadata:
      labels:
        labelName: uuid-api-label
    spec:
      containers:
        - name: uuid-api-container
          image: doridoridoriand/uuid-api:0.0.1
          ports:
            - containerPort: 3000
