---
apiVersion: v1
kind: Service
metadata:
  name: uuid-api-loadbalancer
  namespace: doridoridoriand
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 13000
      targetPort: 3000
  selector:
    app: uuid-api-label
