---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: uuid-api
  namespace: doridoridoriand
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uuid-api
  template:
    metadata:
      labels:
        app: uuid-api
    spec:
      containers:
        - name: uuid-api
          image: doridoridoriand/uuid-api:0.0.1
          ports:
            - containerPort: 3000
