# -*- mode: ruby -*-
# vi: set ft=ruby :

NUMBER_OF_MINION       = 4
MEMORY_CAPACITY_MINION = 4096
CPU_CAPACITY_MINION    = 2

OS = 'ubuntu/bionic64'

VMS = [{vm_name: 'master00', number_of_cpu: 1, memory_capacity: 1024, ip_addr: '192.168.10.10'}]

(1..NUMBER_OF_MINION).to_a.map {|i|
  VMS << {vm_name: "minion#{i.to_s.rjust(2, '0')}",
          number_of_cpu: CPU_CAPACITY_MINION,
          memory_capacity: MEMORY_CAPACITY_MINION,
          ip_addr: "192.168.10.#{10 + i}"}
}

Vagrant.configure(2) do |config|
  VMS.each do |vm|
    config.vm.define vm[:vm_name] do |node|
      node.vm.box = OS
      node.vm.network 'private_network', ip: vm[:ip_addr]
      node.vm.provider 'virtualbox' do |vb|
        vb.memory = vm[:memory_capacity]
        vb.cpus   = vm[:number_of_cpu]
      end

      node.vm.provision 'ansible' do |ansible|
        if vm[:vm_name].include?('master')
          ansible.playbook = 'provision/master.yml'
          ansible.limit    = 'master'
        end
        if vm[:vm_name].include?('minion')
          ansible.playbook = 'provision/minion.yml'
          ansible.limit    = 'minion'
        end
      end
    end
  end
end
