[package]
name = "rust"
version = "0.1.0"
authors = ["doridoridoriand <i.am.eager.for.peace@gmail.com>"]

[dependencies]
uuid = { version = "0.7", features = ["serde", "v4"] }
rocket = "0.4.2"
rocket_contrib = "0.4.2"
serde_derive = "1.0.98"
