---
apiVersion: v1
kind: Service
metadata:
  name: simple-chat-server
spec:
  selector:
    app: simple-chat-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: simple-chat-client
spec:
  selector:
    app: simple-chat-client
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80