# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }


gem 'systemu'
gem 'ipaddress'
gem 'parallel'
gem 'redis'
gem 'pry'

gem 'bundler', :require => [
  'open-uri',
  'json',
  'rexml/document',
  'yaml',
  'logger'
]
