name: "Tokyo Tenki"

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
  schedule:
    - cron: '0 10 * * 1'

jobs:
  analyse:
    name: Analyse
    runs-on: self-hosted
    steps:
      - name: Execute shell script
        run: |
          # ここにシェルスクリプトの内容を記述します
          echo "Hello from shell script"